                      
"""Aggregate srgrape state-growing seed directories.

The N=5 and N=6 rows are generated by running one srgrape
state-growing command per seed.  This helper converts those per-seed
state_grow_summary_*.json files into a rows CSV and a compact summary JSON.
"""

from __future__ import annotations

import argparse
import csv
import json
from pathlib import Path
from statistics import mean, stdev


def latest_summary(seed_dir: Path) -> Path | None:
    paths = sorted(seed_dir.glob("state_grow_summary_*.json"))
    return paths[-1] if paths else None


def row_from_summary(path: Path) -> dict:
    data = json.loads(path.read_text())
    parent = data["parent"]
    child = data["child"]
    seed_text = "".join(ch for ch in path.parent.name if ch.isdigit())
    seed = int(seed_text) if seed_text else int(data.get("args", {}).get("seed", 0))
    return {
        "seed": seed,
        "returncode": 0,
        "wall_s": data.get("total_wall_s", ""),
        "parent_ea_fidelity": parent.get("ea_fidelity", ""),
        "parent_physical_seed_fidelity": parent.get("physical_seed_fidelity", ""),
        "embedded_child_fidelity": child.get("embedded_fidelity", ""),
        "dithered_child_fidelity": child.get("dithered_fidelity", ""),
        "final_child_fidelity": child.get("final_fidelity", ""),
        "best_stage_fidelity": child.get("best_stage_fidelity", ""),
        "iters_to_threshold": child.get("iters_to_threshold", ""),
        "total_stage_iters": child.get("total_stage_iters", ""),
        "child_wall_s": child.get("wall_s", ""),
        "summary_json": str(path),
        "final_controls_path": child.get("final_controls_path", ""),
    }


def write_csv(path: Path, rows: list[dict]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    keys: list[str] = []
    for row in rows:
        for key in row:
            if key not in keys:
                keys.append(key)
    with path.open("w", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=keys)
        writer.writeheader()
        writer.writerows(rows)


def summarize(rows: list[dict], threshold: float) -> dict:
    finals = [float(row["final_child_fidelity"]) for row in rows]
    return {
        "threshold": threshold,
        "n_seeds": len(finals),
        "success_count": sum(x >= threshold for x in finals),
        "success_rate": sum(x >= threshold for x in finals) / len(finals) if finals else 0.0,
        "final_mean": mean(finals) if finals else None,
        "final_std_sample": stdev(finals) if len(finals) > 1 else 0.0,
        "final_min": min(finals) if finals else None,
        "final_max": max(finals) if finals else None,
        "rows": rows,
    }


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--root", type=Path, required=True, help="Directory containing seed01, seed02, ...")
    ap.add_argument("--rows-out", type=Path, required=True)
    ap.add_argument("--summary-out", type=Path, required=True)
    ap.add_argument("--threshold", type=float, default=0.99)
    args = ap.parse_args()

    rows = []
    for seed_dir in sorted(args.root.glob("seed*")):
        if not seed_dir.is_dir():
            continue
        summary_path = latest_summary(seed_dir)
        if summary_path is None:
            rows.append({"seed": seed_dir.name, "returncode": 2, "error": "missing state_grow_summary_*.json"})
            continue
        rows.append(row_from_summary(summary_path))
    rows = sorted(rows, key=lambda row: int(row["seed"]))
    write_csv(args.rows_out, rows)
    payload = summarize([row for row in rows if "final_child_fidelity" in row], args.threshold)
    payload["rows_csv"] = str(args.rows_out)
    args.summary_out.parent.mkdir(parents=True, exist_ok=True)
    args.summary_out.write_text(json.dumps(payload, indent=2, sort_keys=True))
    print(f"wrote {args.rows_out}")
    print(f"wrote {args.summary_out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
